<?xml version="1.0"?>
<package format="3">
  <name>turtlebot3_qt_controller</name>
  <version>1.0.0</version>
  <description>
    Contrôle TurtleBot3 via Qt6 avec caméra et batterie
  </description>
  <maintainer email="votreemailt@btsciel.fr">Etudiant</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>geometry_msgs</depend>
  <depend>sensor_msgs</depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
